FROM node:13.12.0-alpine as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app
COPY public public/
COPY src /app/src

RUN npm install --silent
RUN npm install react-scripts@3.4.1 --silent
RUN npm run build

COPY server.js /app/server.js
COPY .env /app/.env

EXPOSE 10000
